# Generated by Django 3.2.2 on 2021-05-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='document/'),
        ),
    ]
